-- Memory DB Schema
-- PostgreSQL 16+

CREATE SCHEMA IF NOT EXISTS memory;

-- All user <-> assistant conversation across all instances
CREATE TABLE IF NOT EXISTS memory.messages (
  id BIGSERIAL PRIMARY KEY,
  instance TEXT NOT NULL,
  session_id TEXT NOT NULL,
  message_id TEXT NOT NULL,
  parent_id TEXT,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  content TEXT,
  source TEXT,                     -- 'telegram', 'cron:polymarket-operate', etc.
  created_at TIMESTAMPTZ NOT NULL,
  ingested_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(instance, session_id, message_id)
);

CREATE INDEX IF NOT EXISTS idx_messages_content_fts ON memory.messages
  USING gin(to_tsvector('english', content));
CREATE INDEX IF NOT EXISTS idx_messages_created ON memory.messages (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_instance ON memory.messages (instance);
CREATE INDEX IF NOT EXISTS idx_messages_session ON memory.messages (instance, session_id);
CREATE INDEX IF NOT EXISTS idx_messages_role ON memory.messages (role);

-- What crons spit out -- separated for easy querying from main session
CREATE TABLE IF NOT EXISTS memory.cron_reports (
  id BIGSERIAL PRIMARY KEY,
  instance TEXT NOT NULL,
  cron_name TEXT NOT NULL,         -- 'polymarket-operate', '21digital-build', etc.
  session_id TEXT NOT NULL,
  summary TEXT,                    -- the announce/report text
  run_started_at TIMESTAMPTZ,
  run_ended_at TIMESTAMPTZ,
  event_at TIMESTAMPTZ NOT NULL,    -- from transcript timestamp, NOT ingest time
  ingested_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(instance, session_id, cron_name)
);

CREATE INDEX IF NOT EXISTS idx_cron_reports_instance ON memory.cron_reports (instance);
CREATE INDEX IF NOT EXISTS idx_cron_reports_cron ON memory.cron_reports (cron_name);
CREATE INDEX IF NOT EXISTS idx_cron_reports_created ON memory.cron_reports (event_at DESC);
CREATE INDEX IF NOT EXISTS idx_cron_reports_fts ON memory.cron_reports
  USING gin(to_tsvector('english', summary));

-- Session metadata
CREATE TABLE IF NOT EXISTS memory.sessions (
  instance TEXT NOT NULL,
  session_id TEXT NOT NULL,
  started_at TIMESTAMPTZ,
  model TEXT,
  source TEXT,                     -- 'main', 'cron:polymarket-operate', etc.
  message_count INT DEFAULT 0,
  last_synced_byte BIGINT DEFAULT 0,
  last_synced_at TIMESTAMPTZ,
  PRIMARY KEY (instance, session_id)
);

-- Convenience views (auto-generated by sync.js when new instances are discovered)
-- Examples:
-- CREATE VIEW memory.v_entrepreneur AS SELECT * FROM memory.messages WHERE instance = 'entrepreneur';
-- CREATE VIEW memory.v_cron_entrepreneur AS SELECT * FROM memory.cron_reports WHERE instance = 'entrepreneur';
